## These are two functions that can cache values of a matrix inverse
## Lots of comments since I need to remind myself what lines do
## Sorry, I haven't programmed in a decade


## makeCacheMatrix sets and gets the following:
##   1. The matrix where the inversion will be performed (x)
##   2. The inverse of matrix x (i)

makeCacheMatrix <- function(x = matrix()) {
    i <- NULL
    
    # Sets the value of matrix x
    # used when changing the matrix to be inversed
    # if a new matrix is set, the cache will be reset
    set <- function(y = matrix()) {
        x <<- y
        i <<- NULL
    }
    
    # Returns the value fo matrix X
    get <- function() x
    
    # Sets the value of the matrix inverse
    setinverse <- function(inv) i <<- inv
    
    # Returns the value of the matrix inverse
    getinverse <- function() i
    list(set = set, get = get,
         setinverse = setinverse,
         getinverse = getinverse)
    
}


## cacheSolve accepts an object generated by makeCacheMatrix
## This function returns the following:
##      1. IF this is not the first time cacheSolve is called AND 
##            set function has not been used to change matrix x in the meantime
##         THEN the cached matrix inverse is returned
##      2. ELSE solve function will be called to compute the inverse
## 
##NOTE: The function assumes that matrix supplied is always invertable

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    i <- x$getinverse()
    if(!is.null(i)) {
        message("getting cached data")
        return(i)
    }
    data <- x$get()
    i <- solve(data, ...)
    x$setinverse(i)
    i
}
